version: '3.8'

services:
  postgresql:
    image: postgres:12.8
    container_name: db_postgresql
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: talend_persona

  mysql:
    image: mysql:5.7
    container_name: db_mysql
    ports:
      - "6000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talend_escuela
